services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: java
    ports:
      - 5432:5432
    volumes:
      - "./db:/var/lib/postgresql/data"
    networks:
      - postgresql-network
networks:
  postgresql-network:
    driver: bridge
   