spring:
  application:
    name: discovery
  output:
    ansi:
      enabled: always
server:
  port: 8082
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      deafultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
