spring:
  application:
    name: gateway
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        #   lower-case-service-id: true
      routes:
        - id: funcional-service
          uri: lb://webflux-funcional
          predicates:
            - Path=/teste/**
          filters:
            - RewritePath=teste,/
        - id: client-service
          uri: lb://client-service # netflix eureka correspondent service
          predicates:
            - Path=/client/**
server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8082/eureka/
